In [17]:
import pandas as pd
import ast  # To safely evaluate strings containing Python expressions from a string-based input

# Read the main CSV file
df = pd.read_csv('scraped_data_food.csv')
original_rows = len(df)
print("Number of rows in the original CSV file: %d" % len(df))

# Remove duplicate rows with the same 'href', and adjust the index accordingly
df.drop_duplicates(subset='href', inplace=True)
# Reset the index
df.reset_index(drop=True, inplace=True)

print("Number of rows after removing duplicates: %d" % len(df))

print("Number of rows removed: %d" % (original_rows - len(df)))

df

Number of rows in the original CSV file: 14756
Number of rows after removing duplicates: 8950
Number of rows removed: 5806

,href,Sub Area,Name,Search Engine Rating,Sponsored,Opening Hours,Popular Times,Average Star Rating,Individual Star Rating,Reviews,Category,Price Rating,Address,Metadata,Tags,About
0,https://www.google.com/maps/place/Wisma+Atria/...,Depot Road,Wisma Atria,1,Yes,"{'Sunday': [{'open': '10 am', 'close': '10 pm'...","{'Sunday': {'6 am': '0%', '7 am': '0%', '8 am'...",4.2,"{5: 3, 4: 2, 3: 1, 2: 125, 1: 97}",7425,Shopping mall,NAN,"435 Orchard Rd, Singapore 238877","['wismaonline.com', '6235 2103', '8R3M+F8 Sing...","{'food court': 158, 'branded': 66, 'ion orchar...","['In-store shopping', 'Wheelchair-accessible c..."
1,https://www.google.com/maps/place/Chee+Wei+Veg...,Upper Thomson,Chee Wei Vegetarian @ BLK 66 Toa Payoh Lorong 4,1,Yes,"{'Sunday': [{'open': '6 am', 'close': '2 pm'}]...","{'Sunday': {'5 am': '0%', '6 am': '55%', '7 am...",3.7,"{5: 13, 4: 15, 3: 7, 2: 3, 1: 5}",43,Vegetarian restaurant,NAN,"66 Lor 4 Toa Payoh, Singapore 310066","['9747 5776', '8VP2+2R Singapore', 'Send to yo...",{},"['Outdoor seating', 'Takeaway', 'Dine-in', 'Wh..."
2,https://www.google.com/maps/place/Baristart+Co...,Bukit Merah,Baristart Coffee Singapore (Wisma Atria),1,Yes,{},{},4.2,"{5: 23, 4: 9, 3: 2, 2: 2, 1: 3}",39,Cafe,NAN,"435 Orchard Rd, #04-01 Wisma Atria, Singapore ...","['Opens soon ⋅ 11\u202fam', 'Place an order', ...","{'cream puff': 11, 'books': 6, 'pasta': 5, 'la...","['Delivery', 'Takeaway', 'Dine-in', 'Wheelchai..."
3,https://www.google.com/maps/place/JUMBO+Seafoo...,Alexandra North,JUMBO Seafood - Dempsey Hill,1,Yes,"{'Sunday': [{'open': '11:30 am', 'close': '2:3...","{'Sunday': {'6 am': '0%', '7 am': '0%', '8 am'...",4.4,"{5: 1, 4: 772, 3: 200, 2: 64, 1: 66}",2539,Seafood restaurant,Expensive,"11 Dempsey Rd, #01-16, Singapore 249673","['Floor 1 · Dempsey Hill', 'Find a table', 'Pl...","{'chilli crab': 292, 'black pepper crab': 86, ...","['Outdoor seating', 'Takeaway', 'Dine-in', 'Wh..."
4,https://www.google.com/maps/place/Zorba+The+Gr...,Bukit Ho Swee,Zorba The Greek Taverna,1,Yes,{},"{'Sunday': {'6 am': '0%', '7 am': '0%', '8 am'...",4.4,"{5: 1, 4: 267, 3: 87, 2: 55, 1: 73}",1497,Greek restaurant,NAN,"3A River Valley Road, Clarke Quay, Block A ORA...","['Floor 1 · Clarke Quay', 'Open ⋅ Closes 11\u2...","{'river': 103, 'nod': 24, 'beef souvlaki': 20,...","['Outdoor seating', 'Delivery', 'Takeaway', 'D..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8945,https://www.google.com/maps/place/SHARIFARDIAN...,Bukit Batok Central,SHARIFARDIANA,114,No,"{'Sunday': [{'open': '9:30 am', 'close': '9:30...","{'Sunday': {'6 am': '0%', '7 am': '0%', '8 am'...",3.6,"{5: 2, 4: 1, 3: 1, 2: 0, 1: 1}",5,Restaurant,NAN,"134 Bukit Batok West Ave 6, Singapore 650132","['9P2V+MR Singapore', 'Send to your phone', 'C...",{},"['Delivery', 'Takeaway', 'Dine-in', 'Coffee', ..."
8946,https://www.google.com/maps/place/Kimly+Seafoo...,Guilin,Kimly Seafood,17,No,"{'Sunday': [{'open': '11 am', 'close': '2:15 p...","{'Sunday': {'6 am': '0%', '7 am': '0%', '8 am'...",2.6,"{5: 4, 4: 9, 3: 9, 2: 3, 1: 14}",39,Restaurant,Inexpensive,Bukit Batok,['Floor 1 · Bukit Gombak Neighbourhood Centre'...,{'chicken': 8},"['Takeaway', 'Dine-in', 'Wheelchair-accessible..."
8947,https://www.google.com/maps/place/Gimee+Face+%...,Guilin,Gimee Face 给面子,18,No,{},{},2.4,"{5: 0, 4: 2, 3: 1, 2: 2, 1: 2}",7,Noodle shop,NAN,"371 Bukit Batok Street 31, Singapore 650371","['Place an order', '9Q52+Q7 Singapore', 'Send ...",{},"['Takeaway', 'Dine-in', 'Wheelchair-accessible..."
8948,https://www.google.com/maps/place/iO+Italian+O...,Bukit Batok East,iO Italian Osteria,107,No,"{'Sunday': [{'open': '10 am', 'close': '10 pm'...","{'Sunday': {'6 am': '0%', '7 am': '0%', '8 am'...",4.5,"{5: 2, 4: 761, 3: 177, 2: 62, 1: 77}",3215,Italian restaurant,Moderate,"4 Hillview Rise, #02 - 01, Singapore 667979","['Floor 1 · HillV2', 'Find a table', 'Place an...","{'porchetta': 174, 'pork belly': 164, 'schiacc...","['Takeaway', 'Dine-in', 'Wheelchair-accessible..."
8949,https://www.google.com/maps/place/%E9%87%91%E5...,Guilin,金味饭庄 Mixed Vegetable Rice,19,No,{},{},4.0,"{5: 1, 4: 1, 3: 1, 2: 0, 1: 0}",3,Hawker Stall,NAN,"371 Bukit Batok Street 31, Block 372, Singapor...",['Floor 1 · Bukit Gombak Neighbourhood Centre'...,{},"['Takeaway', 'Lunch', 'Casual', 'Good for kids']"

In [18]:
# Write to a new CSV file
df.to_csv('scraped_data_food_processed.csv', index=False)

In [19]:
# Read the reviews CSV file
df = pd.read_csv('scraped_data_reviews_food.csv')


original_rows = len(df)
# Remove duplicate rows with the same 'Review ID'
df.drop_duplicates(subset=['Review ID'], inplace=True)
# Reset the index
df.reset_index(drop=True, inplace=True)

print("Number of rows in the original CSV file: %d" % original_rows)
print("Number of rows after removing duplicates: %d" % len(df))
print("Number of rows removed: %d" % (original_rows - len(df)))

Number of rows in the original CSV file: 65855
Number of rows after removing duplicates: 38166
Number of rows removed: 27689

In [20]:
# Process the 'Date' column to keep only the date part
df['Date'] = pd.to_datetime(df['Date']).dt.date

# Display the date part of df
df['Date']

0               NaT
1        2023-10-28
2               NaT
3        2023-12-28
4               NaT
            ...
38161    2023-12-28
38162           NaT
38163    2023-01-28
38164    2023-01-28
38165    2023-12-28
Name: Date, Length: 38166, dtype: object

In [21]:
import pandas as pd
import ast

# Assuming df is your DataFrame and it already exists

# Safely convert the string representation of list of strings into a list of strings
df['Metadata'] = df['Metadata'].apply(ast.literal_eval)

# Create two new columns "Service Rating" and "Service Type"
df['Service Rating'] = None
df['Service Type'] = None

# Function to process and return the correct value based on the input
def process_value(value, key):
    if "$" in value or key == "Price per person":
        value = value.replace("$", "").replace("RM ", "")
        if "+" in value:
            value = value.replace("+", "")
            return float(value)*1.5
        if "–" in value:
            parts = value.split("–")
            return sum(float(part) for part in parts) / len(parts)
        return float(value)
    try:
        return int(value)
    except ValueError:
        return value

def rating_or_type(value):
    # if integer, then it's a rating
    try:
        int(value)
        return "Service Rating"
    except ValueError:
        return "Service Type"

# Iterate over each row and update the DataFrame with new columns for each key-value pair
for index, metadata_list in enumerate(df['Metadata']):
    for item in metadata_list:
        try:
            key, value = item.split(": ", 1)
            if key == "Service":
                key = rating_or_type(value)
            df.at[index, key] = process_value(value, key)
        except ValueError:
            # print(f"Key has no value: {item}")
            pass

# Drop the columns in which there is less than 20% of non-null values
df.dropna(thresh=len(df) * 0.2, axis=1, inplace=True)


# Drop the original 'Metadata' column
df.drop(columns=['Metadata'], inplace=True)

df

,href of Place,Review ID,Relavancy Ranking,Reviewer href,Reviewer Name,Local Guide,Total Reviews,Total Photos,Star Rating,Date,Review,Service Rating,Service Type,Food,Atmosphere,Meal type,Price per person,Recommended dishes
0,https://www.google.com/maps/place/Wine+Connect...,ChZDSUhNMG9nS0VJQ0FnSUNOa3REdEh3EAE,1,https://www.google.com/maps/contrib/1168593561...,Png Jojo,False,68,322,4,NaT,Ordered the tuna salad and both the tuna and v...,5,None,4.0,5.0,NaN,NaN,NaN
1,https://www.google.com/maps/place/Chee+Wei+Veg...,ChZDSUhNMG9nS0VJQ0FnSURaOHBDaFZnEAE,1,https://www.google.com/maps/contrib/1094554430...,O LY,False,25,3,5,2023-10-28,The young man who mans the stall may seem a li...,5,Dine in,5.0,5.0,Lunch,5.5,Vegetarian Chicken Rice
2,https://www.google.com/maps/place/Baristart+Co...,ChdDSUhNMG9nS0VJQ0FnSUNOMjl2czNBRRAB,1,https://www.google.com/maps/contrib/1177816018...,Danny Fong,True,96,1280,5,NaT,i found this wonderful place nestle in a secti...,None,None,NaN,NaN,NaN,NaN,NaN
3,https://www.google.com/maps/place/Zorba+The+Gr...,ChdDSUhNMG9nS0VJQ0FnSURWc2VEVDlBRRAB,1,https://www.google.com/maps/contrib/1048961498...,Rennie Lee,True,605,1506,5,2023-12-28,"Nice food, nice vibes! The outdoor seating is ...",None,Dine in,NaN,NaN,Dinner,45.0,"Moussaka, Dips Platter Best Seller"
4,https://www.google.com/maps/place/JUMBO+Seafoo...,ChZDSUhNMG9nS0VJQ0FnSUQxNl8zb0xnEAE,1,https://www.google.com/maps/contrib/1029579173...,Mr. Fragile,True,137,325,4,NaT,Food... definitely two Thumbs-up!!! The server...,4,Dine in,5.0,5.0,Dinner,85.0,"Kang Kong Stir Fried with Sambal, Signature Bl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38161,https://www.google.com/maps/place/iO+Italian+O...,ChZDSUhNMG9nS0VJQ0FnSUMxeXFYckJREAE,4,https://www.google.com/maps/contrib/1021334901...,Roha Lee,True,75,446,4,2023-12-28,It's a truly delicious Italian restaurant. Eve...,1,Dine in,5.0,3.0,Lunch,NaN,Tiramisu
38162,https://www.google.com/maps/place/iO+Italian+O...,ChZDSUhNMG9nS0VJQ0FnSUNOOVoyS2F3EAE,5,https://www.google.com/maps/contrib/1143904836...,Estelle Wong,False,4,4,5,NaT,Celebrated my grandfather's birthday and a rea...,5,Dine in,5.0,5.0,Dinner,150.0,"Pistachio Tiramisu, Orecchiette Pork Sausage S..."
38163,https://www.google.com/maps/place/%E9%87%91%E5...,ChZDSUhNMG9nS0VJQ0FnSUQtbHRlSFFBEAE,1,https://www.google.com/maps/contrib/1009288052...,Joshua Chew,True,217,1587,5,2023-01-28,The price is very reasonable for the portion o...,4,Dine in,4.0,5.0,Lunch,NaN,NaN
38164,https://www.google.com/maps/place/%E9%87%91%E5...,ChZDSUhNMG9nS0VJQ0FnSUN1NTdPMWZBEAE,2,https://www.google.com/maps/contrib/1182266810...,Jet Waterbarrel,True,150,68,4,2023-01-28,"Decent food, but not many vegetable options",None,None,NaN,NaN,NaN,NaN,NaN
38165,https://www.google.com/maps/place/%E9%87%91%E5...,ChdDSUhNMG9nS0VJQ0FnSUQtMjdTZ3FnRRAB,3,https://www.google.com/maps/contrib/1040170262...,Lim Lam Sin (Keston),True,579,1532,3,2023-12-28,"13 Dec 23,\n\nFreshly cooked Economical lunch;...",None,None,NaN,NaN,NaN,NaN,NaN

In [22]:
# Write to a new CSV file
df.to_csv('scraped_data_reviews_food_processed.csv', index=False)